server:
  port: 8102
spring:
  application:
    name: eureka-client

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://donghao:123456@localhost:8004/eureka/